# using for production
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dinh-xuan-duong-website-tls # [domain_name-tld của domain]-tls domain_name-tld: là domain-đuôi của domain
type: "kubernetes.io/tls"
spec:
  secretName: dinh-xuan-duong-website
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dinhxuanduong.website
  dnsNames:
    - dinhxuanduong.website
    - www.dinhxuanduong.website
